### ISSUE TITLE
A good nuxt3 modules

### ISSUE THREAD

**Issue by wangzhaohe** [Chris2011/nuxt-asciidoc#1]
Waiting for your commit...

**Comment by Chris2011** [comment]
Thanks for your interest. I'm on it. Maybe in a coule of days, probably weeks. Stay tuned.

**Comment by Chris2011** [comment]
@wangzhaohe the init commit was added, I implemented it and I tested it and it seems to work. Next steps is to write some tests and add the package to npm. Maybe npm first than writing tests.

**Comment by Chris2011** [comment]
@wangzhaohe and here it is: https://www.npmjs.com/package/nuxt-asciidoc please try it and give feedback :)
